- hosts: all
  vars_files:
  - code_vars.yml 
  tasks:
  - name: "Creating folder to be mounted upon"
    file:
     state: directory
     path: "{{ mountfolder }}"

  - name: "Mounting DVD"
    mount:
     src: "/dev/sr0"
     path: "{{ mountfolder }}"
     state: mounted
     fstype: "iso9660"

  - name: "Configure AppStream Repo"
    yum_repository:
     baseurl: "{{ mountfolder }}/AppStream"
     name: "AppStream"
     gpgcheck: no
     description: "AppStream YUM repo from ISO file"

  - name: "Configure BaseOS Repo"
    yum_repository:
     baseurl: "{{ mountfolder }}/BaseOS"
     name: "BaseOS"
     gpgcheck: no
     description: "BaseOS YUM repo from ISO file"

  - name: "Installing apache service"
    package:
     name: "httpd"
     state: present

  - name: "Make Document Root Directory"
    file:
     path: "{{ documentroot }}"
     state: directory

  - name: "Configure SELinux for custom port - Not Recommended Method !!"
    selinux:
     policy: targeted
     state: permissive

  - name: "Configure httpd service"
    template:
     dest: "/etc/httpd/conf.d/lw.conf"
     src: "lw.conf"

  - name: "Configure web pages"
    template:
     dest: "{{ documentroot }}/index.html"
     src: "index.html"

  - name: "Permit Traffic for HTTP"
    firewalld:
     port: "{{ httpdport }}/tcp"
     permanent: yes
     immediate: yes
     state: enabled

  - name: "Configure HTTP Authentication in httpd.conf"
    template:
     dest: "/etc/httpd/conf/httpd.conf"
     src: "httpd.conf"

  - name: "Install python36 for htpasswd"
    package:
     name: "python36"
     state: present

  - name: "Install passlib for htpasswd"
    pip:
     name: "passlib"

  - name: "Creating login credentials"
    htpasswd:
     path: "{{ passwdfile }}/lw.passwd"
     name: "anurag"
     password: "redhat"

  - name: "Configure .htaccess file"
    template:
     dest: "{{ documentroot }}/.htaccess"
     src: "htaccess"

  - name: "Restart HTTP Service"
    service:
     name: "httpd"
     state: restarted
