- name: "Configure Docker Repo"
  import_playbook: docker_yum_repo.yml

- hosts: 192.168.112.129
  tasks: 
  - name: "Installing Docker"
    package: 
     name: "docker-ce-3:18.09.1-3.el7.x86_64"
     state: present

  - name: "Starting Docker Service"
    service:
     name: "docker-ce-18.09.1"
     state: started

  - name: "Pulling the image"
    docker_image:
     name: "alpine"
     source: pull

  - name: "Running the container"
    docker_container:
     name: ansible_test
     image: alpine
     
